language: node_js
node_js: '10'
dist: trusty
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run lint && npm run build && npm run test:travis
addons:
  sauce_connect:
    username: "quill"
    access_key:
      secure: "iGZeDMU8D7d7r/mJXNyPlnlwD4WOEfTpfXkCO9tBdUsmQJq3BlIdugbjOE4VvT2IU9CTyG8tSvHj/UcNOvDVjHv/3Wca4zWUJZ6zunIkE9m4HpyI4bdyWEuz4sfbHhJS8zPiGoRtAvs1z5+liydcfLTXvfWdG64ZLkxUCqDKfhg="
